
services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quotesdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scraper_service
    restart: always
    env_file:
      - ./scraper/.env
    networks:
      - app-network
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_service
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./web/.env
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
